# Full explanations for the General Academic practice set (keyed by global question number 1..140).
# Each: where the answer comes from in the passage/table + why the other options fail.
E = {
1: "Passage, paragraph 2 / Table 1 'Product dimension': (m×n)·(n×p) = m×p, the inner 2s cancel, the outer 3 and 4 remain → 3×4. (a) and (c) mix up inner/outer numbers; (d) is wrong because columns of A (2) equal rows of B (2), so the product is defined.",
2: "Table 1 'Determinant (2×2)': det = ad − bc = 4·5 − 3·2 = 20 − 6 = 14. (b) adds instead of subtracting (20 + 6); (c) forgets bc; (d) uses only bc.",
3: "Passage, paragraph 2: A×B needs (columns of A) = (rows of B), and 'multiplication is generally not commutative'. (a) contradicts non-commutativity; (b) is the rule for addition, not multiplication; (d) is false – a 3×2 times 2×5 gives a non-square 3×5.",
4: "Table 1 'Invertibility': A has an inverse if and only if det(A) ≠ 0. (a) and (b) are not the criterion; (c) is exactly the case in which NO inverse exists.",
5: "Table 1 'Inverse (2×2)': det = 2·3 − 1·5 = 1; swap the diagonal (3, 2), negate the off-diagonal (−1, −5), divide by 1 → (3 −1 / −5 2). (b) is the transpose; (c) forgets to negate; (d) negates the wrong entries.",
6: "Table 1 'Transpose of a product': (A×B)ᵀ = Bᵀ×Aᵀ – the order reverses. (a) keeps the order (the classic trap); (c) and (d) drop the transpose.",
7: "Substitution (last paragraph): from 2x + y = 5, y = 5 − 2x; insert: x + 3(5 − 2x) = 10 → −5x = −5 → x = 1, y = 3. Check the others: (a) 3 + 3 = 6 ≠ 10; (b) 5 + 0 ≠ 10; (c) 2 + 3 ≠ 10.",
8: "Passage, paragraph 1: order irrelevant → C(n,k) = n!/(k!(n−k)!) = C(10,3) = 10·9·8/6 = 120. (b) 720 is the ordered count 10·9·8; (a) and (d) are 10·3 and 10³.",
9: "Table 2 'Arrangements with repeats': LEVEL has 5 letters, L twice and E twice → 5!/(2!·2!) = 120/4 = 30. (c) ignores the repeats; (b) divides only by 2!; (d) divides by too much.",
10: "Classical probability (paragraph 3): 6 favourable pairs (1-6, 2-5, 3-4, 4-3, 5-2, 6-1) of 36 → 6/36 = 1/6. (a) 3/36 counts unordered pairs only; (b) and (c) miscount.",
11: "C(4,2) = 6 ways to place the two heads among 2⁴ = 16 equally likely sequences → 6/16 = 3/8. (a) 1/2 is the chance of a head on one toss; (b) and (c) do not count the 6 arrangements.",
12: "Addition rule with independence (Table 2): P(A or B) = 0.3 + 0.5 − 0.3·0.5 = 0.65. (a) forgets to subtract the overlap; (c) is P(A and B) only; (d) is P(B) only.",
13: "Complement rule (paragraph 3): P(at least one six) = 1 − P(no six) = 1 − (5/6)³ = 1 − 125/216 = 91/216. (b) is P(no six); (a) and (d) = 3·(1/6) wrongly adds probabilities.",
14: "Dependent draws (last paragraph): 5/8 for the first red, then 4 red of 7 remain: 5/8 · 4/7 = 20/56 = 5/14. (a) (5/8)² assumes replacement; (c) is only the first draw; (d) is a guess.",
15: "Log rules (Table 3): product → sum, exponent → factor: log(a³·b) = 3·log(a) + log(b). (b) multiplies the logs; (c) puts the 3 on the wrong factor; (d) subtracts (quotient rule).",
16: "2⁵ = 2·2·2·2·2 = 32 → x = 5. (a) 2⁴ = 16; (c) 2⁶ = 64; (d) 16 = 32/2 confuses the exponent with a division.",
17: "Half-life formula (Table 3): 15 years = 3 half-lives → 80 → 40 → 20 → 10 g. (a) is after one half-life, (b) after two, (d) after four.",
18: "log₂8 = 3 (2³ = 8) and log₂2 = 1 → 3 − 1 = 2 (also: quotient rule log₂(8/2) = log₂4 = 2). (a), (b), (c) mis-evaluate one of the logs.",
19: "Growth factor 3 per hour: 13,500/500 = 27 = 3³ → 3 hours. (b) and (a) do not give 27; (d) confuses the factor 27 with the time.",
20: "Worked example in the passage ('time to reach a target'): 1.05ᵗ = 2 → t·ln(1.05) = ln(2) → t = ln 2 / ln 1.05. (b) inverts the fraction; (c) is not logarithmic; (d) multiplies instead of dividing.",
21: "Last paragraph: exponential growth with factor > 1 eventually exceeds every linear growth. (a) is the reverse; (b) is false (different function types); (c) is false – they can intersect twice or not at all.",
22: "Paragraph 2 / Table 4: binary search halves the search space each step → O(log n). (a) would be independent of n; (c) is a linear scan; (d) is nested comparisons.",
23: "Two nested loops of n → n·n steps → O(n²) (Table 4, quadratic). (a) is one loop; (b) 2ⁿ is exponential; (d) is halving.",
24: "Paragraph 3: for O(n²), (2n)² = 4n² → about 4 times the runtime. (a) would be linear; (b) constant; (c) 8 would be cubic.",
25: "Paragraph 2 order: log n < n < n log n < n² < 2ⁿ. (b), (c), (d) put at least one class in the wrong place (d is fully reversed).",
26: "Paragraph 2: log₂(1,000,000) ≈ 20 comparisons (2²⁰ ≈ 1,048,576). (b)–(d) describe linear-type counts, which binary search avoids.",
27: "Paragraph 1: Big-O gives an upper bound for growth, ignoring constants. (a) it is not seconds; (c) it applies to any algorithm; (d) it is not bytes.",
28: "Paragraph 3 / Table 4: merge sort O(n log n) worst case, quicksort O(n²) worst case. (a) swaps them; (b) neither is O(n); (d) bubble sort is O(n²) and loses for large inputs.",
29: "Place values 8-4-2-1: 1011 = 8 + 0 + 2 + 1 = 11. (a) 1001; (c) 1101 (the passage example); (d) 10111.",
30: "Repeated division by 2 (paragraph 1): 45 = 32 + 8 + 4 + 1 → 101101. Check the others: (b) 110101 = 53, (c) 100101 = 37, (d) 111001 = 57.",
31: "Hex (paragraph 2): 2A = 2·16 + 10 = 42. (a) = 1·16 + 10 (misreads the first digit); (b) = 2·16 without the A; (d) is a miscount.",
32: "De Morgan (last paragraph): NOT(A AND B) = (NOT A) OR (NOT B). (a) is the law for NOT(A OR B); (b) and (c) do not negate correctly.",
33: "XOR is 1 exactly when the inputs differ (truth table, Table 5): A = 1, B = 0. (a) and (b) have equal inputs → 0; (d) is false.",
34: "Paragraph 3: n bits give 2ⁿ values; 2⁸ = 256, unsigned 0–255. (b) forgets 0; (c) is 7 bits; (d) is 9 bits.",
35: "Paragraph 3: a left shift by one position multiplies by 2. (a) is a right shift; (c), (d) are false.",
36: "Complete graph (paragraph 2): n(n−1)/2 = 6·5/2 = 15. (c) 30 forgets to halve (each edge counted twice); (d) 36 = n²; (b) is a miscount.",
37: "Handshake lemma (paragraph 1): degree sum = 2 × edges = 20. (a) forgets the factor 2; (c) halves; (d) – the lemma needs only the edge count.",
38: "Paragraph 2: a tree with n vertices has n − 1 edges → 11. (c) 12 = n (would create a cycle); (a), (b) wrong.",
39: "Paragraph 3: for undirected graphs the adjacency matrix is symmetric (edge i–j = edge j–i). (b), (c), (d) are not implied.",
40: "Compare paths: A–C–D = 3 + 1 = 4, A–B–D = 2 + 4 = 6, A–D = 7 → shortest 4. (a) 3 stops at C; (b) and (d) are the longer paths.",
41: "Paragraph 4: Dijkstra requires all edge weights to be non-negative. (a), (b), (d) are not required.",
42: "Paragraph 4: a connected graph has an Euler circuit iff every vertex has even degree. (a) is the opposite; (b) describes an Euler PATH (two odd vertices), not a circuit; (c) trees have leaves of degree 1.",
43: "v = v₀ + a·t = 0 + 2·5 = 10 m/s (Table 7). (a) is a; (b) is t; (d) 25 is the distance.",
44: "s = ½·a·t² = 0.5·2·25 = 25 m. (b) 10 is the velocity; (c) forgets ½; (d) wrong.",
45: "Free fall with g = 10: s = ½·10·3² = 45 m. (a) forgets t²; (b) = g·t; (d) forgets ½.",
46: "Newton's 2nd law F = m·a = 1500·3 = 4500 N. (a) divides; (b) is m; (c) uses g instead of a.",
47: "Paragraph 3: third law = equal and opposite force pairs. (a) is the first law; (c) the second law; (d) momentum conservation.",
48: "Perfectly inelastic: v = (2·3 + 4·0)/(2 + 4) = 6/6 = 1 m/s. (a), (c), (d) use wrong masses or ignore the resting body.",
49: "First law: constant velocity → no acceleration → net force zero. (b)–(d) would all cause acceleration.",
50: "Boyle's law (Table 8): p·V constant → doubling p halves V. (a) is the inverse; (c), (d) wrong.",
51: "T(K) = 27 + 273 = 300 K. (b) subtracts; (c) forgets the offset; (d) is 100 °C.",
52: "Charles's law: V ∝ T (in kelvin); 300 K → 600 K doubles V: 2 L → 4 L. (a) halves; (b) no change; (d) triples.",
53: "Q = m·c·ΔT = 2·4.2·10 = 84 kJ (worked example pattern). (a) forgets ΔT; (b) forgets m; (c) is 10× too big.",
54: "First law ΔU = Q − W = 500 − 200 = 300 J increase. (a) adds W; (c) wrong sign; (d) wrong.",
55: "pV = nRT with V, T constant → p ∝ n → pressure doubles. (b)–(d) do not follow.",
56: "Paragraph 1: 0 K is the absolute lower limit ≈ −273 °C. (a) confuses 0 K and 0 °C; (b) negative kelvin does not exist; (d) kelvin and Celsius have the same step size.",
57: "Coefficients = mole ratio (paragraph 1): 2 H₂ : 1 O₂ → 4 mol H₂ need 2 mol O₂. (a) halves twice; (c), (d) ignore the ratio.",
58: "pH = −log₁₀[H⁺] = −log₁₀(10⁻³) = 3. (b) is neutral; (c) is 14 − 3; (d) forgets the minus sign.",
59: "Last paragraph: 1 pH unit = factor 10 → 2 units = 100; lower pH = more H⁺ → pH 3 is 100× as concentrated. (a), (b) mis-scale; (d) reverses the direction.",
60: "Le Chatelier (paragraph 2): higher pressure shifts to the side with fewer gas molecules = products here. (b) is the side with more molecules; (a), (c) wrong.",
61: "Molar mass CO₂ = 12 + 2·16 = 44 g/mol → 2 mol = 88 g. (b) is one mole; (a) uses one O; (d) doubles again.",
62: "Paragraph 2: a catalyst accelerates forward and reverse reactions equally → no shift of the equilibrium. (a), (c), (d) all claim a shift/new constant.",
63: "Exothermic + heating → equilibrium shifts back to reactants, yield falls (Table 9). (b) is the opposite; (c), (d) wrong.",
64: "Punnett square (Table 10a): AA : Aa : aa = 1 : 2 : 1, but AA and Aa look alike → phenotype 3 : 1. (c) is the GENOTYPE ratio; (b) is Aa × aa; (d) is a dihybrid cross.",
65: "Aa × aa (paragraph 3): half Aa, half aa → 50 % recessive phenotype. (b) is the Aa × Aa value; (a), (d) wrong.",
66: "Paragraph 1: heterozygous = the two alleles differ. (a) is homozygous; (c), (d) are unrelated definitions.",
67: "Aa × Aa → aa with probability 1/4 = 25 % (Table 10a). (c) is the chance of being a carrier-type Aa; (a), (b) wrong.",
68: "AA and Aa have the same phenotype → different genotypes can look alike. (b) is the reverse (false); (c) causality runs genotype → phenotype; (d) false.",
69: "Two independent traits (paragraph 4): 3:1 × 3:1 → 9 : 3 : 3 : 1. (a) is one trait; (b) is a test cross; (d) is a genotype ratio.",
70: "X-linked (last paragraph): the father gives his X to every daughter (carriers) and his Y to every son (unaffected). (a) reverses the sexes; (b), (c) do not follow.",
71: "Ohm: I = U/R = 12/4 = 3 A. (b) multiplies; (c) inverts; (d) wrong.",
72: "Series: R = 3 + 6 = 9 Ω. (a) is the parallel value; (b) is the average; (d) multiplies.",
73: "Parallel: 1/R = 1/3 + 1/6 = 1/2 → R = 2 Ω – below the smallest resistor, as the passage states. (b)–(d) are not below 3 Ω or are series-type values.",
74: "P = U·I = 230·2 = 460 W. (a) divides; (b) adds; (d) is 10× too big.",
75: "Kirchhoff current law: incoming currents = outgoing currents at every node. (a) is the voltage law; (c) contradicts Ohm's law; (d) false for unequal resistors.",
76: "P = U²/R: doubling U → 4× P (paragraph 4). (b) forgets the square; (a), (c) wrong.",
77: "Paragraph 2: parallel total resistance is smaller than the smallest single resistance. (a) is backwards; (c) is series; (d) is series (same current).",
78: "σ = F/A = 10,000 N / 100 mm² = 100 N/mm² = 100 MPa. (a) forgets kN → N; (c), (d) wrong by factors of 10.",
79: "ε = ΔL/L₀ = 2 mm / 2000 mm = 0.001 (same units!). (b) mixes units; (c) divides 2 by 2; (d) strain has no unit.",
80: "Hooke: E = σ/ε = 200/0.001 = 200,000 MPa. (a) multiplies/ignores ε; (b), (c) wrong powers of ten.",
81: "Area ∝ diameter² → doubling d gives 4× area → stress drops to ¼. (a) is the reverse; (b), (c) forget the square.",
82: "Paragraph 3: elastic = reversible, plastic = permanent. (a) swaps them; (c) plastic is not reversible; (d) plastic starts ABOVE the yield strength.",
83: "Safety factor = yield strength / working stress = 240/80 = 3. (a) is the inverse; (d) is the difference; (b) wrong.",
84: "ε = length/length → dimensionless (paragraph 2). (a) is the unit of stress; (b) is ΔL; (d) E is σ/ε, not ε.",
85: "Sampling theorem (paragraph 2): rate must be more than 2 × 20 kHz = more than 40 kHz. (a), (b) are too low (aliasing); (d) is unnecessarily high, not the minimum.",
86: "Data rate = rate × bits × channels = 44,100 × 16 × 2 = 1,411,200 bit/s (the CD example). (b) is one channel; (a) forgets the bits; (d) doubles again.",
87: "Aliasing occurs when the rate is below twice the highest frequency. (a) bit depth is unrelated; (c) filtering prevents it; (d) is the safe case.",
88: "2⁸ = 256 levels. (a) = 8; (b) = 2⁶; (c) = 2⁷.",
89: "2⁸ = 256 → 2¹⁶ = 65,536. (b) and (c) treat the growth as linear; (d) wrong.",
90: "Paragraph 2: the analogue low-pass filter removes components above half the sampling rate, preventing aliasing. (b)–(d) are not its purpose.",
91: "Interval = 1/rate = 1/1000 s = 1 ms. (a) would be 1 MHz; (c), (d) wrong.",
92: "Assets = equity + liabilities → equity = 500,000 − 300,000 = 200,000 €. (b) is the liabilities; (c) adds; (d) is total assets.",
93: "Equity ratio = equity / total assets = 200,000/500,000 = 40 %. (c) is the debt ratio; (a), (d) wrong.",
94: "Current ratio = current assets / current liabilities = 150,000/100,000 = 1.5. (a) is inverted; (c), (d) are not ratios.",
95: "Paragraph 2: balance sheet = snapshot at a date; income statement = a period. (a), (b), (d) mix these up.",
96: "ROE = profit/equity = 30,000/200,000 = 15 %. (a) divides by total assets; (b), (c) wrong.",
97: "Buying a machine for cash is an asset swap (paragraph 4): one asset up, cash down → total unchanged. (b)–(d) wrong.",
98: "A bank loan is debt capital (liabilities side). (a), (b), (d) are assets.",
99: "Break-even = fixed / contribution margin = 20,000/(50 − 30) = 1,000 units. (a) divides by 50; (b) divides by 30; (d) divides by 10.",
100: "Profit = CM × x − fixed = 20·1500 − 20,000 = 10,000 €. (a), (c), (d) miscount.",
101: "CM per unit = price − variable cost = 50 − 30 = 20 €. (b) is the variable cost; (c) the price; (d) adds.",
102: "Fixed-cost degression (paragraph 1): fixed cost per unit falls as output rises. (a)–(c) contradict this.",
103: "New CM = 60 − 30 = 30 → 20,000/30 ≈ 667 units. (a) divides by 60; (b) = 20,000/40; (d) is the old break-even.",
104: "Raw material varies with output → variable. (b)–(d) are fixed costs (listed in paragraph 1).",
105: "K(x) = 20,000 + 30·800 = 44,000 €. (a) = 30·800 forgets the fixed costs; (c) = 50·800 is the revenue, not the cost; (d) counts the fixed costs twice.",
106: "Elasticity = −20 %/10 % = −2; |−2| > 1 → elastic. (a), (d) invert the fraction; (c) mislabels −2 as inelastic.",
107: "Inelastic demand: quantity falls proportionally less than price rises → revenue rises (paragraph 4). (b) is the elastic case; (c), (d) wrong.",
108: "Set Qd = Qs: 100 − 2p = 20 + 2p → 4p = 80 → p = 20, Q = 60. Check: (a) 70 ≠ 50 at p = 15; (b), (d) do not balance either.",
109: "Paragraph 1: a maximum price below equilibrium creates a shortage (demand > supply). (a) is the minimum-price case; (b), (c) wrong.",
110: "Normal good + rising income → demand curve shifts right (paragraph 2). (a) is the reverse; (c) income is not the good's own price; (d) supply is unaffected.",
111: "Only a change in the good's own price moves along the curve; the other factors shift it. (a), (b), (d) are shift factors.",
112: "Paragraph 3: goods with many substitutes tend to be elastic. (b) necessities are inelastic; (c) false; (d) contradicts the passage.",
113: "Inflation = (110.25 − 105)/105 = 5.25/105 = 5 %. (c) takes the point difference as a percentage; (a), (d) wrong.",
114: "Real ≈ nominal − inflation = 6 − 2 = 4 %. (a) adds; (b), (d) wrong.",
115: "Real GDP = nominal / (deflator/100) = 1050/1.05 = 1000 bn. (c) multiplies by 1.05; (b), (d) wrong.",
116: "Only new production in the period counts (paragraph 1): a house completed this year. (a) resale, (b) transfer, (c) financial asset purchase – none is new production.",
117: "Paragraph 3: the CPI measures the price of a fixed representative basket. (a), (b), (d) are other statistics.",
118: "Deflation = an actual decline of the price level (paragraph 3). (a) is disinflation; (c) inflation; (d) a real-GDP fall.",
119: "GDP per capita = 500 bn / 50 m = 10,000 €. (b)–(d) are off by powers of ten.",
120: "Mean = (2+4+4+6+9)/5 = 25/5 = 5; median = middle value 4. (b) swaps them; (c), (d) miscompute one of them.",
121: "Paragraph 1: the mean reacts strongly to outliers, the median is robust. (a) is reversed; (c), (d) false.",
122: "−0.85 is close to −1 → strong negative linear relationship. (a) wrong sign; (b) wrong strength; (d) correlation ≠ causation.",
123: "Last paragraph: a high correlation can be caused by a third variable. (a), (b) confuse correlation with causation; (c) is not stated/false in general.",
124: "Empirical rule: ≈68 % within mean ± 1 SD = 100 ± 15 → 85 to 115. (b) is ± 2 SD (≈95 %); (c), (d) wrong intervals.",
125: "No dispersion → standard deviation 0. (a), (b), (d) wrong.",
126: "Adding a constant shifts the mean by 5 but keeps distances → SD unchanged. (a), (c), (d) wrong.",
127: "Paragraph 1: random sampling permits generalisation to the population. (b), (c), (d) are not its purpose.",
128: "Last paragraph: reliable-but-invalid scale example → reliable without being valid. (a) defines validity; (c), (d) false.",
129: "Paragraph 2: the control group is the comparison basis that isolates the treatment effect. (a)–(c) wrong.",
130: "Paragraph 3: a confounder influences both the assumed cause and the assumed effect. (a) = independent variable; (b) = dependent; (d) wrong.",
131: "The researcher manipulates the independent variable. (b) is measured; (c), (d) are not manipulated.",
132: "Surveying only one's own course is a convenience sample → weak external validity (generalisability). (a), (c), (d) are not the main threat.",
133: "Only randomised experiments (with control group) permit causal conclusions (paragraph 2). (a)–(c), (d) cannot rule out confounders.",
134: "un- + happy + -ness = 3 morphemes (the passage's worked pattern). (a), (b), (d) miscount.",
135: "Plural -s = inflection (word class unchanged), -ness = derivation (adjective → noun). (a) swaps them; (c), (d) wrong.",
136: "Minimal pair = two words differing in exactly one phoneme and in meaning (pin/bin). (b)–(d) are other notions.",
137: "'meat' lost part of its meaning → narrowing. (b) is the opposite; (c), (d) are unrelated processes.",
138: "Diachronic = change over time. (a) is synchronic; (b), (c) too narrow.",
139: "Hindi and German are both Indo-European (last paragraph). Finnish, Hungarian, Turkish (and Arabic) are not.",
140: "Bound morphemes only occur attached to a stem. (a) describes free morphemes; (c), (d) false.",
}
